package com.bingo.riddle.activity;

import java.util.Timer;
import java.util.TimerTask;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import android.graphics.Color;
import android.os.AsyncTask;
import android.os.Bundle;
import android.util.Log;
import android.view.Gravity;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.widget.TextView;

import com.ads.tool.AdsConstants;
import com.bingo.riddle.db.DBRiddleManager;
import com.bingo.riddle.model.Riddle;
import com.bingo.saying.R;
import com.wandoujia.ads.sdk.Ads;

public class FlashActivity extends Activity {
	private Timer timer;

	// private ViewGroup container;

	// 关于数据操作
	private DBRiddleManager dbRManager = null;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		requestWindowFeature(Window.FEATURE_NO_TITLE);
		setContentView(R.layout.activity_splash);

		timer = new Timer();
		TimerTask task = new TimerTask() {

			@Override
			public void run() {
				initView();
			}
		};
		timer.schedule(task, 1000 * 5);

		new AsyncTask<Void, Void, Boolean>() {
			@Override
			protected Boolean doInBackground(Void... params) {
				try {
					Ads.init(FlashActivity.this, AdsConstants.APP_ID,
							AdsConstants.SECRET_KEY);
					return true;
				} catch (Exception e) {
					Log.e("ads-sample", "error", e);
					return false;
				}
			}

			@Override
			protected void onPostExecute(Boolean success) {
				final ViewGroup container = (ViewGroup) findViewById(R.id.splash_container);

				if (success) {
					/**
					 * pre load
					 */
					Ads.preLoad(AdsConstants.BANNER1, Ads.AdFormat.banner);

					/**
					 * add ad views
					 */
					View bannerView = Ads.createBannerView(FlashActivity.this,
							AdsConstants.BANNER1);
					container.addView(bannerView, new ViewGroup.LayoutParams(
							ViewGroup.LayoutParams.MATCH_PARENT,
							ViewGroup.LayoutParams.WRAP_CONTENT));
				} else {
					TextView errorMsg = new TextView(FlashActivity.this);
					errorMsg.setText("欢迎使用歇后语库");
					errorMsg.setTextColor(Color.RED);
					errorMsg.setTextSize(20);
					errorMsg.setGravity(Gravity.CENTER_HORIZONTAL);
					container.addView(errorMsg);
				}
			}
		}.execute();

		// 数据库操作
		/* 开启一个新线程，在新线程里执行耗时的方法 */
		new Thread(new Runnable() {
			public void run() {
				// if(AppInstalledUtil.isAppInstalled(getApplicationContext(),
				// "com.bingo.lattern"))
				// {
				// System.out.println("========已安装！==");
				// }
				// else {
				// initData();
				// }

				SharedPreferences sharedPreferences = getSharedPreferences(
						"share", MODE_PRIVATE);

				boolean isFirstRun = sharedPreferences.getBoolean("isFirstRun",
						true);
				Editor editor = sharedPreferences.edit();

				if (isFirstRun) {
					Log.e("debug", "第一次运行");
					editor.putBoolean("isFirstRun", false);
					editor.commit();
					initData();
				} else {
					Log.e("debug", "不是第一次运行");
				}
				// 耗时的方法
			}
		}).start();

	}

	private void initView() {
		Intent intent = new Intent(FlashActivity.this,
				MainFragmentActivity.class);
		startActivity(intent);

		this.finish();
	}

	private void initData() {
		dbRManager = new DBRiddleManager(this);

		Riddle riddle1 = new Riddle("	布袋里塞稻秆 	","	 草包	", "经典"	, "无");
		Riddle riddle2 = new Riddle("	缺牙啃西瓜 	","	 道道多	", "经典"	, "无");
		Riddle riddle3 = new Riddle("	黄鹤楼上看行人 	","	 把人看矮了	", "经典"	, "无");
		Riddle riddle4 = new Riddle("	茅坑里捡铜板 	","	 臭钱	", "经典"	, "无");
		Riddle riddle5 = new Riddle("	射击场上的靶子 	","	 漏洞百出	", "经典"	, "无");
		Riddle riddle6 = new Riddle("	蜜糖罐子打醋 	","	 不知酸甜	", "经典"	, "无");
		Riddle riddle7 = new Riddle("	胡子上挂霜 	","	 一吹就了	", "经典"	, "无");
		Riddle riddle8 = new Riddle("	脚踏擀面杖 	","	 立场不稳；左右摇摆；摇摆不定；不稳当	", "经典"	, "无");
		Riddle riddle9 = new Riddle("	玉米棵上戴凉帽 	","	 凑人头	", "经典"	, "无");
		Riddle riddle10 = new Riddle("	跳河闭眼睛 	","	 横了心	", "经典"	, "无");
		Riddle riddle11 = new Riddle("	作坊里的石磨 	","	 推一推，动一动	", "经典"	, "无");
		Riddle riddle12 = new Riddle("	烟袋杆里插席篾儿 	","	 气不顺	", "经典"	, "无");
		Riddle riddle13 = new Riddle("	鼻孔里氏瘤子 	","	 气不顺	", "经典"	, "无");
		Riddle riddle14 = new Riddle("	寒暑表里的水银柱 	","	 能上能下	", "经典"	, "无");
		Riddle riddle15 = new Riddle("	热恋中的情人 	","	 难分开	", "经典"	, "无");
		Riddle riddle16 = new Riddle("	筛子装水 	","	 漏洞百出；漏洞多	", "经典"	, "无");
		Riddle riddle17 = new Riddle("	熟透的大枣 	","	 自来红	", "经典"	, "无");
		Riddle riddle18 = new Riddle("	带刺的铁丝 	","	 难缠	", "经典"	, "无");
		Riddle riddle19 = new Riddle("	傻子活了九十八 	","	 虚度年华	", "经典"	, "无");
		Riddle riddle20 = new Riddle("	扳不倒照镜子 	","	 里外不是人	", "经典"	, "无");
		Riddle riddle21 = new Riddle("	对着聋子打鼓 	","	 充耳不闻	", "经典"	, "无");
		Riddle riddle22 = new Riddle("	豆腐架子 	","	 碰不得；不牢	", "经典"	, "无");
		Riddle riddle23 = new Riddle("	舞台上的皮影戏 	","	 幕后操纵	", "经典"	, "无");
		Riddle riddle24 = new Riddle("	捡个孩子唱大戏 	","	 看你庆哪家的功	", "经典"	, "无");
		Riddle riddle25 = new Riddle("	挖耳勺刨地 	","	 小抠	", "经典"	, "无");
		Riddle riddle26 = new Riddle("	膝盖上打瞌睡 	","	 自己靠自己	", "经典"	, "无");
		Riddle riddle27 = new Riddle("	见了强盗喊爸爸 	","	 认贼作父	", "经典"	, "无");
		Riddle riddle28 = new Riddle("	泥瓦匠出身 	","	 和稀泥	", "经典"	, "无");
		Riddle riddle29 = new Riddle("	十字路口贴告示 	","	 众所周知	", "经典"	, "无");
		Riddle riddle30 = new Riddle("	口吹喇叭脚敲锣 	","	 能者多劳	", "经典"	, "无");
		Riddle riddle31 = new Riddle("	眼前埋地雷 	","	 一触即发	", "经典"	, "无");
		Riddle riddle32 = new Riddle("	一本经书看到老 	","	 墨守成规；食古不化	", "经典"	, "无");
		Riddle riddle33 = new Riddle("	劳动号子 	","	 一呼百应	", "经典"	, "无");
		Riddle riddle34 = new Riddle("	飞机上跳舞 	","	 空喜	", "经典"	, "无");
		Riddle riddle35 = new Riddle("	半道上捡个喇叭 	","	 有吹的了	", "经典"	, "无");
		Riddle riddle36 = new Riddle("	三个小鬼丢了俩 	","	 失魂落魄	", "经典"	, "无");
		Riddle riddle37 = new Riddle("	鞭杆做大梁 	","	 不是正经东西	", "经典"	, "无");
		Riddle riddle38 = new Riddle("	独木桥上遇仇人 	","	 冤家路窄；分外眼红	", "经典"	, "无");
		Riddle riddle39 = new Riddle("	猛将军出征 	","	 不获全胜不收兵	", "经典"	, "无");
		Riddle riddle40 = new Riddle("	老太太吃炒胡豆 	","	 咬牙切齿	", "经典"	, "无");
		Riddle riddle41 = new Riddle("	米筛子当玩具 	","	 耍心眼	", "经典"	, "无");
		Riddle riddle42 = new Riddle("	幺儿子娶媳妇 	","	 大事完毕	", "经典"	, "无");
		Riddle riddle43 = new Riddle("	夫妻推磨 	","	 尽绕圈子；绕圈子	", "经典"	, "无");
		Riddle riddle44 = new Riddle("	吃米不记种田人 	","	 忘本	", "经典"	, "无");
		Riddle riddle45 = new Riddle("	大流子的弟弟 	","	 二流子	", "经典"	, "无");
		Riddle riddle46 = new Riddle("	瞎子跳加官 	","	 盲目乐观	", "经典"	, "无");
		Riddle riddle47 = new Riddle("	杀妻求将 	","	 官迷心窍	", "经典"	, "无");
		Riddle riddle48 = new Riddle("	胭脂当粉搽 	","	 闹了个大红脸	", "经典"	, "无");
		Riddle riddle49 = new Riddle("	森林里撒网 	","	 瞎张罗	", "经典"	, "无");
		Riddle riddle50 = new Riddle("	拿菜刀哄孩子 	","	 不是闹着玩的	", "经典"	, "无");
		Riddle riddle51 = new Riddle("	麻线穿针眼 	","	 过得去就行	", "经典"	, "无");
		Riddle riddle52 = new Riddle("	嗓子里塞棉花 	","	 喘不上气；上气不接下气	", "经典"	, "无");
		Riddle riddle53 = new Riddle("	跛子爬楼梯 	","	 步步难	", "经典"	, "无");
		Riddle riddle54 = new Riddle("	同窑烧的砖瓦 	","	 一路货	", "经典"	, "无");
		Riddle riddle55 = new Riddle("	天灵盖上长眼睛 	","	 目中无人	", "经典"	, "无");
		Riddle riddle56 = new Riddle("	河心搁跳板 	","	 两头脱空	", "经典"	, "无");
		Riddle riddle57 = new Riddle("	大蒜剥皮 	","	 层层深入	", "经典"	, "无");
		Riddle riddle58 = new Riddle("	铁锤打到橡皮上 	","	 一声不响	", "经典"	, "无");
		Riddle riddle59 = new Riddle("	醋坛里酿酒 	","	 坛坛酸	", "经典"	, "无");
		Riddle riddle60 = new Riddle("	抹黑脸照镜子 	","	 自己吓唬自己；自找难看	", "经典"	, "无");
		Riddle riddle61 = new Riddle("	糟鼻子不吃酒 	","	 枉担其名	", "经典"	, "无");
		Riddle riddle62 = new Riddle("	地府里打官司 	","	 死对头	", "经典"	, "无");
		Riddle riddle63 = new Riddle("	六个指头划拳 	","	 出了新招	", "经典"	, "无");
		Riddle riddle64 = new Riddle("	天上的风筝 	","	 一根线在人家手里	", "经典"	, "无");
		Riddle riddle65 = new Riddle("	鞋刷子脱毛 	","	 有板有眼	", "经典"	, "无");
		Riddle riddle66 = new Riddle("	十字路口分手 	","	 各奔前程	", "经典"	, "无");
		Riddle riddle67 = new Riddle("	强拉秀才成亲 	","	 难为圣人	", "经典"	, "无");
		Riddle riddle68 = new Riddle("	纸补裤裆 	","	 越补越烂	", "经典"	, "无");
		Riddle riddle69 = new Riddle("	染匠下河 	","	 大摆布；摆布	", "经典"	, "无");
		Riddle riddle70 = new Riddle("	染坊里卖布 	","	 多管闲事	", "经典"	, "无");
		Riddle riddle71 = new Riddle("	临老学绣花 	","	 晚了；迟了	", "经典"	, "无");
		Riddle riddle72 = new Riddle("	罗锅子上树 	","	 钱	", "经典"	, "无");
		Riddle riddle73 = new Riddle("	掉了帽子喊鞋 	","	 头上一句，脚下一句	", "经典"	, "无");
		Riddle riddle74 = new Riddle("	冷天吞了热汤圆 	","	 身上暖烘烘，心上甜滋滋	", "经典"	, "无");
		Riddle riddle75 = new Riddle("	醋坛里泡枣核 	","	 尖酸	", "经典"	, "无");
		Riddle riddle76 = new Riddle("	穿木屐上高墙 	","	 胆战心惊；战战兢兢	", "经典"	, "无");
		Riddle riddle77 = new Riddle("	逆水行舟 	","	 顶风顶浪	", "经典"	, "无");
		Riddle riddle78 = new Riddle("	姊妹找婆家 	","	 各得其所	", "经典"	, "无");
		Riddle riddle79 = new Riddle("	烂汽车过朽桥 	","	 乘人之危	", "经典"	, "无");
		Riddle riddle80 = new Riddle("	套袖改袜子 	","	 没底儿	", "经典"	, "无");
		Riddle riddle81 = new Riddle("	爬上屋脊的螃蟹 	","	 横行到顶了	", "动物"	, "无");
		Riddle riddle82 = new Riddle("	咸鱼下水 	","	 假新鲜	", "动物"	, "无");
		Riddle riddle83 = new Riddle("	荷花池里养鱼 	","	 一举两得	", "动物"	, "无");
		Riddle riddle84 = new Riddle("	耗子爬铁丝 	","	 难转弯；转不过弯来；转不得身	", "动物"	, "无");
		Riddle riddle85 = new Riddle("	蛤蟆跳到牛背上 	","	 自以为大	", "动物"	, "无");
		Riddle riddle86 = new Riddle("	烟囱里爬老鼠 	","	 直来直去；直进直出；直出直人	", "动物"	, "无");
		Riddle riddle87 = new Riddle("	见惯了骆驼 	","	 看不出牛大来	", "动物"	, "无");
		Riddle riddle88 = new Riddle("	肋条换猪爪 	","	 不上算；不合算	", "动物"	, "无");
		Riddle riddle89 = new Riddle("	耗子嫁女 	","	 讲吃不讲穿	", "动物"	, "无");
		Riddle riddle90 = new Riddle("	高射炮打老鹰 	","	 得不偿失	", "动物"	, "无");
		Riddle riddle91 = new Riddle("	蝎子戴礼帽 	","	 小毒人	", "动物"	, "无");
		Riddle riddle92 = new Riddle("	螃蟹教子 	","	 不走正道	", "动物"	, "无");
		Riddle riddle93 = new Riddle("	河边上逮螃蟹 	","	 有一个捉一个	", "动物"	, "无");
		Riddle riddle94 = new Riddle("	找擀杖摸到牛犄角 	","	 别扭出穹儿来了	", "动物"	, "无");
		Riddle riddle95 = new Riddle("	骆驼撒欢 	","	 汉个正经样	", "动物"	, "无");
		Riddle riddle96 = new Riddle("	老太太吃牛筋 	","	 食而不知其味	", "动物"	, "无");
		Riddle riddle97 = new Riddle("	老鼠给大象指路 	","	 越走越窄	", "动物"	, "无");
		Riddle riddle98 = new Riddle("	俩螃蟹打架 	","	 纠缠不清	", "动物"	, "无");
		Riddle riddle99 = new Riddle("	猴子拉车 	","	 又蹦又跳；连蹦带跳	", "动物"	, "无");
		Riddle riddle100 = new Riddle("	蒸馍打狗 	","	 有去无回	", "动物"	, "无");
		Riddle riddle101 = new Riddle("	捏死手中鸟 	","	 轻而易举	", "动物"	, "无");
		Riddle riddle102 = new Riddle("	死了的啄木鸟 	","	 好硬的嘴；嘴硬	", "动物"	, "无");
		Riddle riddle103 = new Riddle("	豹子进山 	","	 浑身是胆	", "动物"	, "无");
		Riddle riddle104 = new Riddle("	牛棚里养鸡 	","	 架子不小；好大的架子	", "动物"	, "无");
		Riddle riddle105 = new Riddle("	猪八戒吃西瓜 	","	 独吞	", "动物"	, "无");
		Riddle riddle106 = new Riddle("	牛牵鼻子马抓鬃 	","	 抓住了关键	", "动物"	, "无");
		Riddle riddle107 = new Riddle("	天然牛黄 	","	 宝贝疙瘩	", "动物"	, "无");
		Riddle riddle108 = new Riddle("	锦鸡进铁笼 	","	 身不由已；不由自主	", "动物"	, "无");
		Riddle riddle109 = new Riddle("	孙猴子上天宫 	","	 得意忘形	", "动物"	, "无");
		Riddle riddle110 = new Riddle("	狐狸钻罐子 	","	 藏头露尾	", "动物"	, "无");
		Riddle riddle111 = new Riddle("	正月十五的走马灯 	","	 反复无常	", "动物"	, "无");
		Riddle riddle112 = new Riddle("	笼里捉鸡 	","	 十拿九稳	", "动物"	, "无");
		Riddle riddle113 = new Riddle("	城隍爷扑蝴蝶 	","	 慌了神	", "动物"	, "无");
		Riddle riddle114 = new Riddle("	耗子找枪 	","	 窝里反	", "动物"	, "无");
		Riddle riddle115 = new Riddle("	老母猪啃砖头 	","	 好硬的嘴	", "动物"	, "无");
		Riddle riddle116 = new Riddle("	锅堂里的老鼠 	","	 灰溜溜	", "动物"	, "无");
		Riddle riddle117 = new Riddle("	黑泥鳅钻进金鱼缸 	","	 谁跟你比美；光显自己漂亮；献丑	", "动物"	, "无");
		Riddle riddle118 = new Riddle("	捂着眼睛捉麻雀 	","	 瞎摸	", "动物"	, "无");
		Riddle riddle119 = new Riddle("	老母猪啃猪圈 	","	 嘴巴痒了	", "动物"	, "无");
		Riddle riddle120 = new Riddle("	叫牛坐板凳 	","	 办不到；没法办	", "动物"	, "无");
		Riddle riddle121 = new Riddle("	猴子拉弓 	","	 不是样子	", "动物"	, "无");
		Riddle riddle122 = new Riddle("	风箱里的老鼠 	","	 两头受气	", "动物"	, "无");
		Riddle riddle123 = new Riddle("	蜗牛赴宴 	","	 不速之客	", "动物"	, "无");
		Riddle riddle124 = new Riddle("	草地上捉鸭子 	","	 干扑	", "动物"	, "无");
		Riddle riddle125 = new Riddle("	黄毛鸭子下水 	","	 不知深浅	", "动物"	, "无");
		Riddle riddle126 = new Riddle("	柏油烫猪头 	","	 连根拔	", "动物"	, "无");
		Riddle riddle127 = new Riddle("	打鱼子碰烂船 	","	 倾家荡产	", "动物"	, "无");
		Riddle riddle128 = new Riddle("	请狼来做客 	","	 活得不耐烦	", "动物"	, "无");
		Riddle riddle129 = new Riddle("	马食槽边点盏灯 	","	 照料	", "动物"	, "无");
		Riddle riddle130 = new Riddle("	梁头上吊王八 	","	 四脚无靠	", "动物"	, "无");
		Riddle riddle131 = new Riddle("	黑天捉牛 	","	 摸不着角	", "动物"	, "无");
		Riddle riddle132 = new Riddle("	老鼠给猫捋胡子 	","	 送死；自己找死	", "动物"	, "无");
		Riddle riddle133 = new Riddle("	脚踩牛屎 	","	 一塌糊涂	", "动物"	, "无");
		Riddle riddle134 = new Riddle("	老虎拖象 	","	 大干一场	", "动物"	, "无");
		Riddle riddle135 = new Riddle("	碓窝里放鸡蛋 	","	 求稳	", "动物"	, "无");
		Riddle riddle136 = new Riddle("	三分钱买个臭猪蹄 	","	 贱货	", "动物"	, "无");
		Riddle riddle137 = new Riddle("	秧鸡子下田 	","	 顾头不顾尾	", "动物"	, "无");
		Riddle riddle138 = new Riddle("	买死鱼放生 	","	 荒唐；不知死活	", "动物"	, "无");
		Riddle riddle139 = new Riddle("	赶车不带鞭子 	","	 光拍马屁	", "动物"	, "无");
		Riddle riddle140 = new Riddle("	驴尾巴吊棒槌 	","	 累赘	", "动物"	, "无");
		Riddle riddle141 = new Riddle("	老子偷猪儿偷牛 	","	 一辈更比一辈坏	", "动物"	, "无");
		Riddle riddle142 = new Riddle("	灯草套牯牛 	","	 动不得	", "动物"	, "无");
		Riddle riddle143 = new Riddle("	独木桥上跑马 	","	 冒险；危险	", "动物"	, "无");
		Riddle riddle144 = new Riddle("	猴子戴金冠 	","	 惹祸大王	", "动物"	, "无");
		Riddle riddle145 = new Riddle("	房檐上逮鸡 	","	 不好捉弄	", "动物"	, "无");
		Riddle riddle146 = new Riddle("	马蜂蜇秃子 	","	 头痛；没遮没盖	", "动物"	, "无");
		Riddle riddle147 = new Riddle("	老牛吃草 	","	 吞吞吐吐	", "动物"	, "无");
		Riddle riddle148 = new Riddle("	兔子拉车 	","	 不懂那一套；又蹦又跳；连蹦带跳	", "动物"	, "无");
		Riddle riddle149 = new Riddle("	跪在老虎面前喊恩人 	","	 善恶不分	", "动物"	, "无");
		Riddle riddle150 = new Riddle("	狗尾巴上系鞭炮 	","	 追着炸	", "动物"	, "无");
		Riddle riddle151 = new Riddle("	老虎近身 	","	 开口是祸	", "动物"	, "无");
		Riddle riddle152 = new Riddle("	水牛抓跳蚤 	","	 有劲使不上	", "动物"	, "无");
		Riddle riddle153 = new Riddle("	耗子钻风箱 	","	 两头咬气；自找罪受	", "动物"	, "无");
		Riddle riddle154 = new Riddle("	老母猪打架 	","	 全凭一张嘴；全仗嘴	", "动物"	, "无");
		Riddle riddle155 = new Riddle("	买咸鱼放生 	","	 尽做冤枉事	", "动物"	, "无");
		Riddle riddle156 = new Riddle("	马脸比猪头 	","	 当面出丑；一个比一个丑	", "动物"	, "无");
		Riddle riddle157 = new Riddle("	马戏团的猴子 	","	 任人耍；由人玩耍	", "动物"	, "无");
		Riddle riddle158 = new Riddle("	牛奶里掺墨汁 	","	 黑白混淆	", "动物"	, "无");
		Riddle riddle159 = new Riddle("	猪八戒不成仙 	","	 吃了嘴的亏；全坏在嘴上	", "动物"	, "无");
		Riddle riddle160 = new Riddle("	绑着腿的青蛙 	","	 跳不了啦	", "动物"	, "无");
		Riddle riddle161 = new Riddle("	恶狗咬天 	","	 狂妄	", "谐音"	, "无");
		Riddle riddle162 = new Riddle("	河里拉屎 	","	 只有他自己知道	", "谐音"	, "无");
		Riddle riddle163 = new Riddle("	歪嘴吹号 	","	 正气不足，邪气有余	", "谐音"	, "无");
		Riddle riddle164 = new Riddle("	司令上树 	","	 趾高气扬	", "谐音"	, "无");
		Riddle riddle165 = new Riddle("	蛤蟆跳到热锅上 	","	 欢乐一时是一时	", "谐音"	, "无");
		Riddle riddle166 = new Riddle("	荞麦窝里扎锥子 	","	 奸对奸	", "谐音"	, "无");
		Riddle riddle167 = new Riddle("	船到码头车到站 	","	 停滞不前	", "谐音"	, "无");
		Riddle riddle168 = new Riddle("	吃多了盐 	","	 尽讲闲话	", "谐音"	, "无");
		Riddle riddle169 = new Riddle("	三间房子不开门 	","	 怪物	", "谐音"	, "无");
		Riddle riddle170 = new Riddle("	茶壶里煮馄饨 	","	 一肚子话	", "谐音"	, "无");
		Riddle riddle171 = new Riddle("	老鼠跑进食盒里 	","	 抓住理了	", "谐音"	, "无");
		Riddle riddle172 = new Riddle("	湿水的大鼓 	","	 不想	", "谐音"	, "无");
		Riddle riddle173 = new Riddle("	西施上庵堂 	","	 美妙	", "谐音"	, "无");
		Riddle riddle174 = new Riddle("	当兵的背算盘 	","	 找仗打	", "谐音"	, "无");
		Riddle riddle175 = new Riddle("	十冬腊月出房门 	","	 动手动	", "谐音"	, "无");
		Riddle riddle176 = new Riddle("	张飞摆屠案 	","	 凶神恶熬	", "谐音"	, "无");
		Riddle riddle177 = new Riddle("	老鼠咬旗杆 	","	 吃不到	", "谐音"	, "无");
		Riddle riddle178 = new Riddle("	大水冲了菩萨 	","	 绝妙	", "谐音"	, "无");
		Riddle riddle179 = new Riddle("	小朋友唱歌 	","	 同声同	", "谐音"	, "无");
		Riddle riddle180 = new Riddle("	笛子配唢呐 	","	 想得不一样	", "谐音"	, "无");
		Riddle riddle181 = new Riddle("	大船载太阳 	","	 勉强度日	", "谐音"	, "无");
		Riddle riddle182 = new Riddle("	唢呐里吹出笛子调 	","	 想不到一块；想	", "谐音"	, "无");
		Riddle riddle183 = new Riddle("	捏着鼻子吃葱 	","	 忍气吞声	", "谐音"	, "无");
		Riddle riddle184 = new Riddle("	下雨往屋里跑 	","	 淋不到	", "谐音"	, "无");
		Riddle riddle185 = new Riddle("	三两银子放账 	","	 稀少	", "谐音"	, "无");
		Riddle riddle186 = new Riddle("	自留地里拉屎 	","	 泄私愤	", "谐音"	, "无");
		Riddle riddle187 = new Riddle("	三九天穿裙子 	","	 美丽又动人	", "谐音"	, "无");
		Riddle riddle188 = new Riddle("	腊月三十洗长衫 	","	 今年不干明年干	", "谐音"	, "无");
		Riddle riddle189 = new Riddle("	垃圾堆里的八骏图 	","	 废话	", "谐音"	, "无");
		Riddle riddle190 = new Riddle("	说书的收了三弦琴 	","	 不谈了	", "谐音"	, "无");
		Riddle riddle191 = new Riddle("	老虎舔糨糊 	","	 不够煳嘴	", "谐音"	, "无");
		Riddle riddle192 = new Riddle("	北极的另一端 	","	 难极	", "谐音"	, "无");
		Riddle riddle193 = new Riddle("	冰凌调豆腐 	","	 难办	", "谐音"	, "无");
		Riddle riddle194 = new Riddle("	南天门作揖 	","	 高情难	", "谐音"	, "无");
		Riddle riddle195 = new Riddle("	庄稼老不识桂圆 	","	 外行	", "谐音"	, "无");
		Riddle riddle196 = new Riddle("	拿着扫帚上杏树 	","	 扫杏	", "谐音"	, "无");
		Riddle riddle197 = new Riddle("	牛屁股后的苍蝇 	","	 一哄而散；盯上不放	", "谐音"	, "无");
		Riddle riddle198 = new Riddle("	桅杆顶上吹唢呐 	","	 四方闻名	", "谐音"	, "无");
		Riddle riddle199 = new Riddle("	茅房里的大粪蛆 	","	 死里求生	", "谐音"	, "无");
		Riddle riddle200 = new Riddle("	狐狸吵架 	","	 一派胡言	", "谐音"	, "无");
		Riddle riddle201 = new Riddle("	外婆得了个小儿子 	","	 有救了	", "谐音"	, "无");
		Riddle riddle202 = new Riddle("	城隍出主意 	","	 诡计多端	", "谐音"	, "无");
		Riddle riddle203 = new Riddle("	胡琴与琵琶合奏 	","	 谈到一块去了	", "谐音"	, "无");
		Riddle riddle204 = new Riddle("	老虎拉车 	","	 没人敢；不听那一套	", "谐音"	, "无");
		Riddle riddle205 = new Riddle("	腊八儿出生 	","	 动手动	", "谐音"	, "无");
		Riddle riddle206 = new Riddle("	拾粪老汉起五更 	","	 找死；寻死	", "谐音"	, "无");
		Riddle riddle207 = new Riddle("	盐店的老板转行 	","	 不管闲事	", "谐音"	, "无");
		Riddle riddle208 = new Riddle("	黄花鱼下挂面 	","	 不用言	", "谐音"	, "无");
		Riddle riddle209 = new Riddle("	同吹两把号 	","	 想到一块了	", "谐音"	, "无");
		Riddle riddle210 = new Riddle("	虾子掉在大麦上 	","	 忙上加忙	", "谐音"	, "无");
		Riddle riddle211 = new Riddle("	米汤泡稀饭 	","	 亲上加亲	", "谐音"	, "无");
		Riddle riddle212 = new Riddle("	铁匠拉风箱 	","	 柔能克刚	", "谐音"	, "无");
		Riddle riddle213 = new Riddle("	棉花铺失火 	","	 谈不得；无法谈	", "谐音"	, "无");
		Riddle riddle214 = new Riddle("	眼皮上吊炊帚 	","	 耍嘴	", "谐音"	, "无");
		Riddle riddle215 = new Riddle("	弹花匠上殿 	","	 有功之臣	", "谐音"	, "无");
		Riddle riddle216 = new Riddle("	泥人吃饼子 	","	 难言	", "谐音"	, "无");
		Riddle riddle217 = new Riddle("	大车拉煎饼 	","	 贪得多	", "谐音"	, "无");
		Riddle riddle218 = new Riddle("	落雨立当院 	","	 轮到头上	", "谐音"	, "无");
		Riddle riddle219 = new Riddle("	破棉袄 	","	 里外孬	", "谐音"	, "无");
		Riddle riddle220 = new Riddle("	半天云里挂口袋 	","	 装疯	", "谐音"	, "无");
		Riddle riddle221 = new Riddle("	打着灯笼拾粪 	","	 找死	", "谐音"	, "无");
		Riddle riddle222 = new Riddle("	不拨灯不添油 	","	 省心	", "谐音"	, "无");
		Riddle riddle223 = new Riddle("	刀马旦不会刀枪 	","	 笨蛋；徒有虚名	", "谐音"	, "无");
		Riddle riddle224 = new Riddle("	懒婆娘上鸡窝 	","	 笨蛋	", "谐音"	, "无");
		Riddle riddle225 = new Riddle("	敲锣碰到放炮的 	","	 想到一点子上	", "谐音"	, "无");
		Riddle riddle226 = new Riddle("	半夜不见枪头子 	","	 攮	", "谐音"	, "无");
		Riddle riddle227 = new Riddle("	烂屁股蜘蛛 	","	 没事	", "谐音"	, "无");
		Riddle riddle228 = new Riddle("	虾子掉在盐堆里 	","	 忙中有闲	", "谐音"	, "无");
		Riddle riddle229 = new Riddle("	吃咸菜长大的 	","	 尽管闲事	", "谐音"	, "无");
		Riddle riddle230 = new Riddle("	又敲锣鼓又放炮 	","	 想到一块了	", "谐音"	, "无");
		Riddle riddle231 = new Riddle("	放路纸钱 	","	 瘾死人	", "谐音"	, "无");
		Riddle riddle232 = new Riddle("	五朵梅花开一朵 	","	 四肢无力	", "谐音"	, "无");
		Riddle riddle233 = new Riddle("	庙台上长草 	","	 慌了神	", "谐音"	, "无");
		Riddle riddle234 = new Riddle("	两个人打排球 	","	 推来推去；互相推脱	", "谐音"	, "无");
		Riddle riddle235 = new Riddle("	远洋轮出海 	","	 外行	", "谐音"	, "无");
		Riddle riddle236 = new Riddle("	山坡上烤火 	","	 就地取材	", "谐音"	, "无");
		Riddle riddle237 = new Riddle("	茅坑里的搅屎棍 	","	 文不能文	", "谐音"	, "无");
		Riddle riddle238 = new Riddle("	卖煎饼的赔本 	","	 贪大了	", "谐音"	, "无");
		Riddle riddle239 = new Riddle("	梁山泊的军师 	","	 无用	", "谐音"	, "无");
		Riddle riddle240 = new Riddle("	肉骨头打鼓 	","	 昏冬冬	", "谐音"	, "无");
		Riddle riddle241 = new Riddle("	开春的鸟儿 	","	 成双成对	", "季节"	, "无");
		Riddle riddle242 = new Riddle("	过冬的大葱 	","	 皮焦根枯心不死；叶烂皮干心不死	", "季节"	, "无");
		Riddle riddle243 = new Riddle("	夏夜走棋 	","	 星罗棋布	", "季节"	, "无");
		Riddle riddle244 = new Riddle("	冬天不戴帽子 	","	 动脑筋	", "季节"	, "无");
		Riddle riddle245 = new Riddle("	春笋破土 	","	 节节高；天天向上	", "季节"	, "无");
		Riddle riddle246 = new Riddle("	临嫁的姑娘 	","	 满面春风；春风满面	", "季节"	, "无");
		Riddle riddle247 = new Riddle("	夏天的袜子 	","	 可有可无	", "季节"	, "无");
		Riddle riddle248 = new Riddle("	春苗得雨 	","	 正逢时	", "季节"	, "无");
		Riddle riddle249 = new Riddle("	笼里的斑鸠 	","	 不知春秋	", "季节"	, "无");
		Riddle riddle250 = new Riddle("	千年铁树开了花 	","	 枯木逢春；得之不易；今古奇观	", "季节"	, "无");
		Riddle riddle251 = new Riddle("	穿寒衣摇夏扇 	","	 不知冷热	", "季节"	, "无");
		Riddle riddle252 = new Riddle("	一江春水向东流 	","	 滚滚向前；无穷无尽	", "季节"	, "无");
		Riddle riddle253 = new Riddle("	春天的杨柳 	","	 分外亲	", "季节"	, "无");
		Riddle riddle254 = new Riddle("	春汛的鱼虾 	","	 随大流	", "季节"	, "无");
		Riddle riddle255 = new Riddle("	返青的秋苗 	","	 节节高；节节上升	", "季节"	, "无");
		Riddle riddle256 = new Riddle("	春蚕到死 	","	 怀着丝	", "季节"	, "无");
		Riddle riddle257 = new Riddle("	夏天的扇子 	","	 人人欢喜；个个喜爱	", "季节"	, "无");
		Riddle riddle258 = new Riddle("	秋后的南瓜 	","	 皮老心不老	", "季节"	, "无");
		Riddle riddle259 = new Riddle("	夏天的烘笼 	","	 没用处；挂起来了	", "季节"	, "无");
		Riddle riddle260 = new Riddle("	洞庭湖里涨春水 	","	 一浪高一浪	", "季节"	, "无");
		Riddle riddle261 = new Riddle("	李时珍看病 	","	 手到病除；妙手回春	", "季节"	, "无");
		Riddle riddle262 = new Riddle("	冬天的竹笋 	","	 出不了头	", "季节"	, "无");
		Riddle riddle263 = new Riddle("	高粱撒在麦地里 	","	 杂种；秋后见高低	", "季节"	, "无");
		Riddle riddle264 = new Riddle("	开春的兔子 	","	 成群结伙	", "季节"	, "无");
		Riddle riddle265 = new Riddle("	秋天剥黄麻 	","	 扯皮	", "季节"	, "无");
		Riddle riddle266 = new Riddle("	穿冬衣摇夏扇 	","	 不知冷热	", "季节"	, "无");
		Riddle riddle267 = new Riddle("	炎夏天的火炉子 	","	 讨人嫌	", "季节"	, "无");
		Riddle riddle268 = new Riddle("	舅老爷请春客 	","	 奉陪到底	", "季节"	, "无");
		Riddle riddle269 = new Riddle("	冬天的蚂蚁 	","	 不露头	", "季节"	, "无");
		Riddle riddle270 = new Riddle("	冬天火炉夏天扇 	","	 个个喜爱	", "季节"	, "无");
		Riddle riddle271 = new Riddle("	踩虎尾，踏春冰 	","	 冒险	", "季节"	, "无");
		Riddle riddle272 = new Riddle("	秋后的知了 	","	 没几天叫头	", "季节"	, "无");
		Riddle riddle273 = new Riddle("	冬天吃梅子 	","	 寒酸	", "季节"	, "无");
		Riddle riddle274 = new Riddle("	寒冬的电扇 	","	 令人生畏	", "季节"	, "无");
		Riddle riddle275 = new Riddle("	秋后的蚂蚱 	","	 没几天蹦头；蹦达不了几天	", "季节"	, "无");
		Riddle riddle276 = new Riddle("	春草闹堂 	","	 急中生智	", "季节"	, "无");
		Riddle riddle277 = new Riddle("	画上的春牛 	","	 中看不中用	", "季节"	, "无");
		Riddle riddle278 = new Riddle("	冬天的扇子，夏天的火炉 	","	 没人爱	", "季节"	, "无");
		Riddle riddle279 = new Riddle("	秋后的核桃 	","	 满人	", "季节"	, "无");
		Riddle riddle280 = new Riddle("	早春的桃花 	","	 红不久	", "季节"	, "无");
		Riddle riddle281 = new Riddle("	刺笆林里的斑鸠 	","	 不知春秋	", "季节"	, "无");
		Riddle riddle282 = new Riddle("	秋后的蚊子 	","	 嗡嗡不了几天；销声匿迹	", "季节"	, "无");
		Riddle riddle283 = new Riddle("	石头缝里常春藤 	","	 两受夹；两头受挤根子硬	", "季节"	, "无");
		Riddle riddle284 = new Riddle("	秋天的柿子 	","	 自来红	", "季节"	, "无");
		Riddle riddle285 = new Riddle("	冬天贩冰棒 	","	 不懂买卖经；不识时务	", "季节"	, "无");
		Riddle riddle286 = new Riddle("	秋后的丝瓜 	","	 满肚子私；一肚子私	", "季节"	, "无");
		Riddle riddle287 = new Riddle("	春茶尖儿 	","	 又鲜又嫩	", "季节"	, "无");
		Riddle riddle288 = new Riddle("	冬天的大葱 	","	 皮干叶烂心不死	", "季节"	, "无");
		Riddle riddle289 = new Riddle("	秋后的扇子 	","	 没人过问	", "季节"	, "无");
		Riddle riddle290 = new Riddle("	秋后的蛤蟆 	","	 没几天叫头	", "季节"	, "无");
		Riddle riddle291 = new Riddle("	药王爷的匾 	","	 手到病除；妙手回春	", "季节"	, "无");
		Riddle riddle292 = new Riddle("	冬水田里种麦子 	","	 怪哉	", "季节"	, "无");
		Riddle riddle293 = new Riddle("	春凳折了靠背儿 	","	 无靠	", "季节"	, "无");
		Riddle riddle294 = new Riddle("	炎夏天打冷战 	","	 不寒而栗	", "季节"	, "无");
		Riddle riddle295 = new Riddle("	冬天卖扇子 	","	 过时货	", "季节"	, "无");
		Riddle riddle296 = new Riddle("	春天的雷，涨潮的水 	","	 留不住	", "季节"	, "无");
		Riddle riddle297 = new Riddle("	夏天的萤火虫 	","	 若明若暗	", "季节"	, "无");
		Riddle riddle298 = new Riddle("	夏天的火炉 	","	 挨不得	", "季节"	, "无");
		Riddle riddle299 = new Riddle("	秋蝉落地 	","	 闷声不响；闷声闷气；哑了	", "季节"	, "无");
		Riddle riddle300 = new Riddle("	年画上的春牛 	","	 离不得	", "季节"	, "无");
		Riddle riddle301 = new Riddle("	冬天穿汗衫 	","	 冷暖自己知	", "季节"	, "无");
		Riddle riddle302 = new Riddle("	新娶的媳妇 	","	 春风满面	", "季节"	, "无");
		Riddle riddle303 = new Riddle("	冬天买扇子 	","	 备用	", "季节"	, "无");
		Riddle riddle304 = new Riddle("	春天的草芽 	","	 自发	", "季节"	, "无");
		Riddle riddle305 = new Riddle("	秋后望田头 	","	 找茬儿	", "季节"	, "无");
		Riddle riddle306 = new Riddle("	冬天的旋风 	","	 成不了气候	", "季节"	, "无");
		Riddle riddle307 = new Riddle("	春天的石榴花 	","	 心红	", "季节"	, "无");
		Riddle riddle308 = new Riddle("	冬天泡桐树 	","	 光棍一条	", "季节"	, "无");
		Riddle riddle309 = new Riddle("	冬天进豆腐房 	","	 好大的气	", "季节"	, "无");
		Riddle riddle310 = new Riddle("	老柳树发新芽 	","	 回春	", "季节"	, "无");
		Riddle riddle311 = new Riddle("	冬天的蟒蛇 	","	 有气无力	", "季节"	, "无");
		Riddle riddle312 = new Riddle("	穿凉鞋戴棉帽 	","	 顾头不顾脚；不知春秋	", "季节"	, "无");
		Riddle riddle313 = new Riddle("	穿棉衣打扇 	","	 不知春秋	", "季节"	, "无");
		Riddle riddle314 = new Riddle("	冬天的暖水瓶 	","	 外冷内热	", "季节"	, "无");
		Riddle riddle315 = new Riddle("	壁上的春牛 	","	 离不得；跟	", "季节"	, "无");
		Riddle riddle316 = new Riddle("	冬天的炉子 	","	 闲不着	", "季节"	, "无");
		Riddle riddle317 = new Riddle("	开春的柳絮 	","	 满天飞	", "季节"	, "无");
		Riddle riddle318 = new Riddle("	冬天的螃蟹 	","	 横行不了几时	", "季节"	, "无");
		Riddle riddle319 = new Riddle("	春天的竹笋 	","	 节节向上；无依	", "季节"	, "无");
		Riddle riddle320 = new Riddle("	冬天吃葡萄 	","	 寒酸	", "季节"	, "无");
		Riddle riddle321 = new Riddle("	屎壳郎嫁蝽象 	","	 臭味相投	", "昆虫"	, "无");
		Riddle riddle322 = new Riddle("	蚂蚁脖子戳一刀 	","	 不是出血的筒子	", "昆虫"	, "无");
		Riddle riddle323 = new Riddle("	屎壳郎推车 	","	 滚蛋	", "昆虫"	, "无");
		Riddle riddle324 = new Riddle("	嗑瓜子瞌出个臭虫 	","	 充人来了	", "昆虫"	, "无");
		Riddle riddle325 = new Riddle("	蜜蜂的窝 	","	 窟窿多	", "昆虫"	, "无");
		Riddle riddle326 = new Riddle("	屎壳郎滚粪蛋 	","	 走回头路；倒退	", "昆虫"	, "无");
		Riddle riddle327 = new Riddle("	一枪打死个苍蝇 	","	 得不偿失	", "昆虫"	, "无");
		Riddle riddle328 = new Riddle("	笼子里关蚂蚁 	","	 来去自由	", "昆虫"	, "无");
		Riddle riddle329 = new Riddle("	灭虱子烧皮袄 	","	 因小失大	", "昆虫"	, "无");
		Riddle riddle330 = new Riddle("	扇蒲扇打蚊子 	","	 一举两得	", "昆虫"	, "无");
		Riddle riddle331 = new Riddle("	缚在线上的蚂蚱 	","	 跑不了	", "昆虫"	, "无");
		Riddle riddle332 = new Riddle("	蚂蚁驮秤砣 	","	 好大的口气	", "昆虫"	, "无");
		Riddle riddle333 = new Riddle("	秋后的蚊子 	","	 嗡嗡不了几天；销声匿迹	", "昆虫"	, "无");
		Riddle riddle334 = new Riddle("	裤子里进蚂蚁 	","	 坐立不安	", "昆虫"	, "无");
		Riddle riddle335 = new Riddle("	蚂蚁回窝 	","	 走老路	", "昆虫"	, "无");
		Riddle riddle336 = new Riddle("	玻璃罩里的苍蝇 	","	 看到光明无出路；处处碰壁	", "昆虫"	, "无");
		Riddle riddle337 = new Riddle("	哑巴被蜈蚣咬 	","	 痛不可言	", "昆虫"	, "无");
		Riddle riddle338 = new Riddle("	蚂蚁拉石磙 	","	 力不能及；力不从心；心有余而力不足	", "昆虫"	, "无");
		Riddle riddle339 = new Riddle("	苍蝇找屎克螂做亲 	","	 臭味相投	", "昆虫"	, "无");
		Riddle riddle340 = new Riddle("	蚊子放屁 	","	 小气	", "昆虫"	, "无");
		Riddle riddle341 = new Riddle("	大象吃蚊子 	","	 无从下口；无法下口；难下	", "昆虫"	, "无");
		Riddle riddle342 = new Riddle("	蜜蜂蛰人 	","	 逼急	", "昆虫"	, "无");
		Riddle riddle343 = new Riddle("	无头的苍蝇 	","	 瞎碰；瞎撞	", "昆虫"	, "无");
		Riddle riddle344 = new Riddle("	蚂蚁戴谷壳 	","	 好大的脸皮	", "昆虫"	, "无");
		Riddle riddle345 = new Riddle("	马槽里的苍蝇 	","	 混饭吃	", "昆虫"	, "无");
		Riddle riddle346 = new Riddle("	蜜蜂的屁股 	","	 刺儿头	", "昆虫"	, "无");
		Riddle riddle347 = new Riddle("	蚂蚱爬在鞭梢上 	","	 经不起摔打	", "昆虫"	, "无");
		Riddle riddle348 = new Riddle("	口水沾跳蚤 	","	 一物降一物	", "昆虫"	, "无");
		Riddle riddle349 = new Riddle("	蚂蚱看庄稼 	","	 越看越光	", "昆虫"	, "无");
		Riddle riddle350 = new Riddle("	墙上的蜘蛛网，草原上的脚印 	","	 蛛丝马迹	", "昆虫"	, "无");
		Riddle riddle351 = new Riddle("	蛤蟆吃萤火虫 	","	 心里亮；肚里明	", "昆虫"	, "无");
		Riddle riddle352 = new Riddle("	蚂蚱跳塘 	","	 不知深浅	", "昆虫"	, "无");
		Riddle riddle353 = new Riddle("	飞蛾撵蜘蛛 	","	 自投网罗	", "昆虫"	, "无");
		Riddle riddle354 = new Riddle("	放大镜照臭虫 	","	 原形毕露	", "昆虫"	, "无");
		Riddle riddle355 = new Riddle("	冬天的蚂蚁 	","	 不露头	", "昆虫"	, "无");
		Riddle riddle356 = new Riddle("	蜂蜜待客 	","	 给他点甜头	", "昆虫"	, "无");
		Riddle riddle357 = new Riddle("	屎壳郎出国 	","	 臭名远扬	", "昆虫"	, "无");
		Riddle riddle358 = new Riddle("	蜜蜂叮镜中花 	","	 白费功夫	", "昆虫"	, "无");
		Riddle riddle359 = new Riddle("	烂肉喂苍蝇 	","	 投其所好	", "昆虫"	, "无");
		Riddle riddle360 = new Riddle("	恨虱子烧棉袄 	","	 得不偿失；不值得	", "昆虫"	, "无");
		Riddle riddle361 = new Riddle("	蚊子飞到电灯上 	","	 弃暗投明	", "昆虫"	, "无");
		Riddle riddle362 = new Riddle("	苍蝇洗脸 	","	 假干净	", "昆虫"	, "无");
		Riddle riddle363 = new Riddle("	蚂蚁头上砍一刀 	","	 没血肉	", "昆虫"	, "无");
		Riddle riddle364 = new Riddle("	蚊子叮鸡蛋 	","	 无孔不入；无缝可钻	", "昆虫"	, "无");
		Riddle riddle365 = new Riddle("	蚂蚁搬秤砣 	","	 白费功夫；白费劲；枉费功	", "昆虫"	, "无");
		Riddle riddle366 = new Riddle("	屎壳郎戴面具 	","	 臭不要脸	", "昆虫"	, "无");
		Riddle riddle367 = new Riddle("	惊蛰后的蜈蚣 	","	 越来越凶	", "昆虫"	, "无");
		Riddle riddle368 = new Riddle("	屎壳郎爬鞭梢 	","	 光知腾云驾雾，不知死在跟前	", "昆虫"	, "无");
		Riddle riddle369 = new Riddle("	掉进浆糊盆里的苍蝇 	","	 拔不出腿来	", "昆虫"	, "无");
		Riddle riddle370 = new Riddle("	蚊子咬木偶 	","	 找错了对象	", "昆虫"	, "无");
		Riddle riddle371 = new Riddle("	蚂蚁生疮 	","	 小毛病	", "昆虫"	, "无");
		Riddle riddle372 = new Riddle("	断了翅膀的苍蝇 	","	 嗡嗡不了几天	", "昆虫"	, "无");
		Riddle riddle373 = new Riddle("	屎壳郎跌粪坑 	","	 饱餐一顿；死里求生	", "昆虫"	, "无");
		Riddle riddle374 = new Riddle("	大吊车吊蚂蚁 	","	 轻而易举	", "昆虫"	, "无");
		Riddle riddle375 = new Riddle("	苍蝇放屁 	","	 吓谁哩	", "昆虫"	, "无");
		Riddle riddle376 = new Riddle("	屎壳郎放屁 	","	 不值一文	", "昆虫"	, "无");
		Riddle riddle377 = new Riddle("	屎壳郎打饱嗝儿 	","	 满嘴喷粪	", "昆虫"	, "无");
		Riddle riddle378 = new Riddle("	屎壳郎戴耳环 	","	 摆臭阔气	", "昆虫"	, "无");
		Riddle riddle379 = new Riddle("	蚂蚁抖腿 	","	 小踢蹬	", "昆虫"	, "无");
		Riddle riddle380 = new Riddle("	蚂蚁下塘 	","	 不知深浅	", "昆虫"	, "无");
		Riddle riddle381 = new Riddle("	蚊子趴在玻璃上 	","	 插不上嘴；难插嘴	", "昆虫"	, "无");
		Riddle riddle382 = new Riddle("	蚊子的力气 	","	 大不了	", "昆虫"	, "无");
		Riddle riddle383 = new Riddle("	蜂儿没嘴 	","	 屁股伤人	", "昆虫"	, "无");
		Riddle riddle384 = new Riddle("	蚂蚁抬食 	","	 步调一致	", "昆虫"	, "无");
		Riddle riddle385 = new Riddle("	掐了头的苍蝇 	","	 乱撞；不知死活；死活不知	", "昆虫"	, "无");
		Riddle riddle386 = new Riddle("	春天的蜜蜂 	","	 闲不住	", "昆虫"	, "无");
		Riddle riddle387 = new Riddle("	蚂蚁碰上鸡 	","	 活该	", "昆虫"	, "无");
		Riddle riddle388 = new Riddle("	光头上面长虱子 	","	 无处藏身	", "昆虫"	, "无");
		Riddle riddle389 = new Riddle("	嗑瓜子嗑出个臭虫来 	","	 什么仁儿都有	", "昆虫"	, "无");
		Riddle riddle390 = new Riddle("	屎壳郎坐飞机 	","	 臭气熏天；一步登天	", "昆虫"	, "无");
		Riddle riddle391 = new Riddle("	苍蝇钻到瓶瓶里 	","	 处处碰壁	", "昆虫"	, "无");
		Riddle riddle392 = new Riddle("	鸡屎蚊子打哈欠 	","	 好大的气魄	", "昆虫"	, "无");
		Riddle riddle393 = new Riddle("	屎壳郎跌炉灶 	","	 凶多吉少	", "昆虫"	, "无");
		Riddle riddle394 = new Riddle("	苍蝇叮大粪 	","	 臭味相投	", "昆虫"	, "无");
		Riddle riddle395 = new Riddle("	蚂蚁进牢房 	","	 自有出路	", "昆虫"	, "无");
		Riddle riddle396 = new Riddle("	屎壳郎戴花 	","	 臭美	", "昆虫"	, "无");
		Riddle riddle397 = new Riddle("	吃蜂蜜说好话 	","	 甜言蜜语	", "昆虫"	, "无");
		Riddle riddle398 = new Riddle("	蚂蚁扛大树 	","	 不自量	", "昆虫"	, "无");
		Riddle riddle399 = new Riddle("	无蜜的蜂房 	","	 空空洞洞	", "昆虫"	, "无");
		Riddle riddle400 = new Riddle("	屎壳郎爬在算盘上 	","	 混账	", "昆虫"	, "无");
		Riddle riddle401 = new Riddle("	钟馗嫁妹 	","	 鬼混	", "人物"	, "无");
		Riddle riddle402 = new Riddle("	潘金莲的信条 	","	 宁在花下死，做鬼也风流	", "人物"	, "无");
		Riddle riddle403 = new Riddle("	阎王桌上抓供果 	","	 送死	", "人物"	, "无");
		Riddle riddle404 = new Riddle("	武大郎捉奸 	","	 力不能及；反被害了性命	", "人物"	, "无");
		Riddle riddle405 = new Riddle("	财神爷戴乌纱帽 	","	 钱也有，权也有	", "人物"	, "无");
		Riddle riddle406 = new Riddle("	张果老骑驴 	","	 倒着走	", "人物"	, "无");
		Riddle riddle407 = new Riddle("	龙王爷出阵 	","	 翻江倒海	", "人物"	, "无");
		Riddle riddle408 = new Riddle("	财神爷招手 	","	 来福了	", "人物"	, "无");
		Riddle riddle409 = new Riddle("	桅杆顶上耍把戏 	","	 爬得高，跌得重；武艺高	", "人物"	, "无");
		Riddle riddle410 = new Riddle("	孙猴子跳出水帘洞 	","	 好戏在后头	", "人物"	, "无");
		Riddle riddle411 = new Riddle("	掀菩萨烧庙宇 	","	 无恶不作	", "人物"	, "无");
		Riddle riddle412 = new Riddle("	武大郎的扁担 	","	 长不了	", "人物"	, "无");
		Riddle riddle413 = new Riddle("	猪八戒戴耳环 	","	 自以为美	", "人物"	, "无");
		Riddle riddle414 = new Riddle("	唐僧遇见白骨精 	","	 敌我不分	", "人物"	, "无");
		Riddle riddle415 = new Riddle("	判官办案 	","	 吓死人	", "人物"	, "无");
		Riddle riddle416 = new Riddle("	猪八戒娶媳妇 	","	 痴心妄想	", "人物"	, "无");
		Riddle riddle417 = new Riddle("	阎王爷好见 	","	 小鬼难缠	", "人物"	, "无");
		Riddle riddle418 = new Riddle("	贾宝玉看林妹妹 	","	 见如故	", "人物"	, "无");
		Riddle riddle419 = new Riddle("	儿子打老子 	","	 情理难容；无法无天；岂有此理	", "人物"	, "无");
		Riddle riddle420 = new Riddle("	阎王爷说谎 	","	 骗鬼	", "人物"	, "无");
		Riddle riddle421 = new Riddle("	孙悟空变山神庙 	","	 露了尾巴	", "人物"	, "无");
		Riddle riddle422 = new Riddle("	孙悟空听见紧箍咒 	","	 头痛	", "人物"	, "无");
		Riddle riddle423 = new Riddle("	才脱了阎王，又撞着小鬼 	","	 祸不单行	", "人物"	, "无");
		Riddle riddle424 = new Riddle("	孙悟空手里的金箍棒 	","	 随心所欲	", "人物"	, "无");
		Riddle riddle425 = new Riddle("	孙悟空保唐僧 	","	 忠心耿耿；降妖拿怪	", "人物"	, "无");
		Riddle riddle426 = new Riddle("	猪八戒招亲 	","	 黑灯黑人	", "人物"	, "无");
		Riddle riddle427 = new Riddle("	孔夫子游列国 	","	 尽是礼	", "人物"	, "无");
		Riddle riddle428 = new Riddle("	悬崖上翻跟头 	","	 送死；自己找死；凶多吉少	", "人物"	, "无");
		Riddle riddle429 = new Riddle("	曹操背时遇蒋干，胡豆背时遇稀饭 	","	 倒霉透了	", "人物"	, "无");
		Riddle riddle430 = new Riddle("	猪八戒抡家伙 	","	 倒打一耙	", "人物"	, "无");
		Riddle riddle431 = new Riddle("	墙上挂钟馗 	","	 鬼话	", "人物"	, "无");
		Riddle riddle432 = new Riddle("	刘备卖草鞋 	","	 本行	", "人物"	, "无");
		Riddle riddle433 = new Riddle("	掖着个孙悟空 	","	 憋出个猴来	", "人物"	, "无");
		Riddle riddle434 = new Riddle("	海龙王吃螃蟹 	","	 敲骨吸髓	", "人物"	, "无");
		Riddle riddle435 = new Riddle("	猪八戒挎腰刀 	","	 邋遢	", "人物"	, "无");
		Riddle riddle436 = new Riddle("	白骨精扮新娘 	","	 娇里妖气	", "人物"	, "无");
		Riddle riddle437 = new Riddle("	教菩萨认字 	","	 枉费心机	", "人物"	, "无");
		Riddle riddle438 = new Riddle("	钱塘江里洗被单 	","	 大摆布	", "人物"	, "无");
		Riddle riddle439 = new Riddle("	钟馗受骗 	","	 被鬼迷往	", "人物"	, "无");
		Riddle riddle440 = new Riddle("	灶王爷跌跟头 	","	 砸锅了	", "人物"	, "无");
		Riddle riddle441 = new Riddle("	灶王爷吹灯 	","	 好神气	", "人物"	, "无");
		Riddle riddle442 = new Riddle("	猪八戒戴眼镜 	","	 冒充斯文；假斯文	", "人物"	, "无");
		Riddle riddle443 = new Riddle("	包公升堂 	","	 尽管直说	", "人物"	, "无");
		Riddle riddle444 = new Riddle("	许仙碰着白娘子 	","	 天降良缘	", "人物"	, "无");
		Riddle riddle445 = new Riddle("	孔夫子偷钱包 	","	 文明人不做文明事	", "人物"	, "无");
		Riddle riddle446 = new Riddle("	猪八戒西天取经 	","	 三心二意	", "人物"	, "无");
		Riddle riddle447 = new Riddle("	菩萨坐冷庙 	","	 孤苦怜订	", "人物"	, "无");
		Riddle riddle448 = new Riddle("	深山小庙的菩萨 	","	 没见过大香火；没人侍奉；默默无闻	", "人物"	, "无");
		Riddle riddle449 = new Riddle("	猪八戒喝磨刀水 	","	 内秀；秀	", "人物"	, "无");
		Riddle riddle450 = new Riddle("	刘备遇孔明 	","	 如鱼得水	", "人物"	, "无");
		Riddle riddle451 = new Riddle("	判官讨饭 	","	 穷鬼	", "人物"	, "无");
		Riddle riddle452 = new Riddle("	张果老倒骑驴 	","	 背道而驰；不见畜牲面；往后看	", "人物"	, "无");
		Riddle riddle453 = new Riddle("	玉帝爷的帽子 	","	 宝贝疙瘩	", "人物"	, "无");
		Riddle riddle454 = new Riddle("	灶王爷打飞脚 	","	 离板了	", "人物"	, "无");
		Riddle riddle455 = new Riddle("	猪八戒啃猪蹄 	","	 忘了自个儿姓名；自残骨肉	", "人物"	, "无");
		Riddle riddle456 = new Riddle("	买鱼放生 	","	 菩萨心肠	", "人物"	, "无");
		Riddle riddle457 = new Riddle("	玻璃菩萨 	","	 神明	", "人物"	, "无");
		Riddle riddle458 = new Riddle("	诸葛亮吊孝 	","	 假仁假义	", "人物"	, "无");
		Riddle riddle459 = new Riddle("	丢下灶王拜山神 	","	 舍近求远	", "人物"	, "无");
		Riddle riddle460 = new Riddle("	二郎神斗孙悟空 	","	 以变应变；你变我也变	", "人物"	, "无");
		Riddle riddle461 = new Riddle("	泥菩萨擂流 	","	 难过	", "人物"	, "无");
		Riddle riddle462 = new Riddle("	假李逵碰真李逵 	","	 冤家路窄	", "人物"	, "无");
		Riddle riddle463 = new Riddle("	判官玩魔术 	","	 鬼把戏	", "人物"	, "无");
		Riddle riddle464 = new Riddle("	当着阎王告判官 	","	 没有好下场	", "人物"	, "无");
		Riddle riddle465 = new Riddle("	黄鼠狼间难卦 	","	 凶多吉少	", "人物"	, "无");
		Riddle riddle466 = new Riddle("	阎王爷做的芝麻饼 	","	 鬼点子多	", "人物"	, "无");
		Riddle riddle467 = new Riddle("	教观音菩萨识字 	","	 枉费心机	", "人物"	, "无");
		Riddle riddle468 = new Riddle("	贾宝玉结婚 	","	 不是心上人	", "人物"	, "无");
		Riddle riddle469 = new Riddle("	挑水骑单车 	","	 武艺高；本领高	", "人物"	, "无");
		Riddle riddle470 = new Riddle("	张飞遇李逵 	","	 黑对黑；黑上加黑	", "人物"	, "无");
		Riddle riddle471 = new Riddle("	诸葛亮用空城计 	","	 不得己	", "人物"	, "无");
		Riddle riddle472 = new Riddle("	吃曹操的饭，想刘备的事 	","	 人在心不在	", "人物"	, "无");
		Riddle riddle473 = new Riddle("	苍蝇叮菩萨 	","	 没有人味	", "人物"	, "无");
		Riddle riddle474 = new Riddle("	猪八戒吃大肉 	","	 忘本	", "人物"	, "无");
		Riddle riddle475 = new Riddle("	白骨精见了孙悟空 	","	 现原形了	", "人物"	, "无");
		Riddle riddle476 = new Riddle("	破庙里的菩萨 	","	 东倒西歪	", "人物"	, "无");
		Riddle riddle477 = new Riddle("	李逵绣花 	","	 力不能及；力不从心	", "人物"	, "无");
		Riddle riddle478 = new Riddle("	孙猴子的屁股 	","	 坐不住；坐不稳	", "人物"	, "无");
		Riddle riddle479 = new Riddle("	孙猴子上天宫 	","	 得意忘形	", "人物"	, "无");
		Riddle riddle480 = new Riddle("	阎王老子谈家常 	","	 尽讲鬼话	", "人物"	, "无");
		Riddle riddle481 = new Riddle("	大年三十的烟火 	","	 万紫千红	", "节气"	, "无");
		Riddle riddle482 = new Riddle("	大年三十晚上熬稀饭 	","	 年关难过	", "节气"	, "无");
		Riddle riddle483 = new Riddle("	月亮坝里掷色子 	","	 观点模糊	", "节气"	, "无");
		Riddle riddle484 = new Riddle("	三十晚上走路 	","	 没影子	", "节气"	, "无");
		Riddle riddle485 = new Riddle("	月亮跟着太阳转 	","	 沾光；借光	", "节气"	, "无");
		Riddle riddle486 = new Riddle("	大年初一拜年 	","	 你好我也好	", "节气"	, "无");
		Riddle riddle487 = new Riddle("	三伏天喝冰水 	","	 正中下怀	", "节气"	, "无");
		Riddle riddle488 = new Riddle("	十五的月亮 	","	 完美无缺；圆圆满满	", "节气"	, "无");
		Riddle riddle489 = new Riddle("	三伏天絮棉袄 	","	 闲时预备忙时用	", "节气"	, "无");
		Riddle riddle490 = new Riddle("	三九天的冰棍 	","	 没人理	", "节气"	, "无");
		Riddle riddle491 = new Riddle("	天亮下大雪 	","	 明白；明明白白	", "节气"	, "无");
		Riddle riddle492 = new Riddle("	三十三颗荞麦九十九道棱 	","	 一成不变	", "节气"	, "无");
		Riddle riddle493 = new Riddle("	月亮下点油灯 	","	 多事	", "节气"	, "无");
		Riddle riddle494 = new Riddle("	元宵里裹爆竹 	","	 糖衣炮弹	", "节气"	, "无");
		Riddle riddle495 = new Riddle("	初七八的月亮 	","	 半边阴	", "节气"	, "无");
		Riddle riddle496 = new Riddle("	大年初一看历书 	","	 日子长着哩	", "节气"	, "无");
		Riddle riddle497 = new Riddle("	踩凳子够月亮 	","	 差远了	", "节气"	, "无");
		Riddle riddle498 = new Riddle("	苞谷面做元宵 	","	 捏不拢	", "节气"	, "无");
		Riddle riddle499 = new Riddle("	三九天穿裙子 	","	 美丽又动人	", "节气"	, "无");
		Riddle riddle500 = new Riddle("	正月十五的月亮 	","	 光明正大	", "节气"	, "无");
		Riddle riddle501 = new Riddle("	三九天的豆腐干 	","	 冷冰冰，硬邦邦	", "节气"	, "无");
		Riddle riddle502 = new Riddle("	叭拉狗咬月亮 	","	 不知天多高	", "节气"	, "无");
		Riddle riddle503 = new Riddle("	三九天扇扇子 	","	 心里有火	", "节气"	, "无");
		Riddle riddle504 = new Riddle("	和尚跟着月亮走 	","	 借光了	", "节气"	, "无");
		Riddle riddle505 = new Riddle("	三九天喝姜汤 	","	 热心肠	", "节气"	, "无");
		Riddle riddle506 = new Riddle("	三伏天的狗 	","	 喘不上气；上气不接下气	", "节气"	, "无");
		Riddle riddle507 = new Riddle("	孩子们过年 	","	 常盼那一天	", "节气"	, "无");
		Riddle riddle508 = new Riddle("	下大雪找蹄印 	","	 罕见	", "节气"	, "无");
		Riddle riddle509 = new Riddle("	大年初一借袍子 	","	 不识时务；不是时候	", "节气"	, "无");
		Riddle riddle510 = new Riddle("	铁拐李看月亮 	","	 上不正，下参羡	", "节气"	, "无");
		Riddle riddle511 = new Riddle("	哈巴狗咬月亮 	","	 不知天高地厚；不知高低	", "节气"	, "无");
		Riddle riddle512 = new Riddle("	年三十夜拨算盘 	","	 满打满算	", "节气"	, "无");
		Riddle riddle513 = new Riddle("	叫花子碰上大雪天 	","	 饥寒交迫	", "节气"	, "无");
		Riddle riddle514 = new Riddle("	太阳和月亮讲话 	","	 空谈	", "节气"	, "无");
		Riddle riddle515 = new Riddle("	过年敲锅盖 	","	 穷得丁当响	", "节气"	, "无");
		Riddle riddle516 = new Riddle("	月亮地里晒被单 	","	 白搭	", "节气"	, "无");
		Riddle riddle517 = new Riddle("	三十晚上借蒸笼 	","	 不是时候	", "节气"	, "无");
		Riddle riddle518 = new Riddle("	大年初一翻皇历 	","	 头一回；头一遭	", "节气"	, "无");
		Riddle riddle519 = new Riddle("	东方天亮下大雪 	","	 明明白白；明白	", "节气"	, "无");
		Riddle riddle520 = new Riddle("	三伏天穿皮袄 	","	 不是时候，不识时务；乱套了	", "节气"	, "无");
		Riddle riddle521 = new Riddle("	端午节拜年 	","	 不是时候	", "节气"	, "无");
		Riddle riddle522 = new Riddle("	三九天掉冰窟 	","	 抖起来了	", "节气"	, "无");
		Riddle riddle523 = new Riddle("	端午节包粽子 	","	 有棱有角	", "节气"	, "无");
		Riddle riddle524 = new Riddle("	穷债户过年 	","	 躲躲闪闪	", "节气"	, "无");
		Riddle riddle525 = new Riddle("	墨汁煮元宵 	","	 漆黑一团；一团漆黑	", "节气"	, "无");
		Riddle riddle526 = new Riddle("	大年初一贴福字 	","	 吉庆有余	", "节气"	, "无");
		Riddle riddle527 = new Riddle("	人过三十不学艺 	","	 老了	", "节气"	, "无");
		Riddle riddle528 = new Riddle("	过年借礼帽 	","	 不识时务	", "节气"	, "无");
		Riddle riddle529 = new Riddle("	大年初一打平伙 	","	 穷凑合	", "节气"	, "无");
		Riddle riddle530 = new Riddle("	纸糊的月亮当太阳 	","	 偷天换日	", "节气"	, "无");
		Riddle riddle531 = new Riddle("	三伏天孵小鸡 	","	 坏蛋；坏蛋多	", "节气"	, "无");
		Riddle riddle532 = new Riddle("	站在河岸捞月亮 	","	 白搭工	", "节气"	, "无");
		Riddle riddle533 = new Riddle("	大年三十喂年猪 	","	 来不及了	", "节气"	, "无");
		Riddle riddle534 = new Riddle("	三九天谈心 	","	 冷言冷语	", "节气"	, "无");
		Riddle riddle535 = new Riddle("	盼望月亮从西出 	","	 没指望	", "节气"	, "无");
		Riddle riddle536 = new Riddle("	拿着碾盘打月亮 	","	 不知轻重	", "节气"	, "无");
		Riddle riddle537 = new Riddle("	天上的月亮 	","	 看得见，摸不着	", "节气"	, "无");
		Riddle riddle538 = new Riddle("	三九天的叫花子 	","	 又冷又饿	", "节气"	, "无");
		Riddle riddle539 = new Riddle("	三伏天的电扇 	","	 忙得团团转	", "节气"	, "无");
		Riddle riddle540 = new Riddle("	晾衣竿钩月亮 	","	 差天远	", "节气"	, "无");
		Riddle riddle541 = new Riddle("	大年三十盼月亮 	","	 痴心妄想；妄想	", "节气"	, "无");
		Riddle riddle542 = new Riddle("	元宵掉进肉锅里 	","	 说他混蛋，他还心里甜	", "节气"	, "无");
		Riddle riddle543 = new Riddle("	三九天桃花开 	","	 罕见；太离奇；稀奇古怪	", "节气"	, "无");
		Riddle riddle544 = new Riddle("	柳条篮子摇元宵 	","	 滚蛋	", "节气"	, "无");
		Riddle riddle545 = new Riddle("	娃娃过年 	","	 真快活；不操心；光图吃；只讲吃；蹦得欢	", "节气"	, "无");
		Riddle riddle546 = new Riddle("	端午节划龙舟 	","	 载歌载舞	", "节气"	, "无");
		Riddle riddle547 = new Riddle("	三伏天的隔夜饭 	","	 臭货	", "节气"	, "无");
		Riddle riddle548 = new Riddle("	年三十夜的年糕 	","	 人有我有；你有我也有	", "节气"	, "无");
		Riddle riddle549 = new Riddle("	月亮坝里耍弯刀 	","	 明砍	", "节气"	, "无");
		Riddle riddle550 = new Riddle("	猴子捞月亮 	","	 一场空	", "节气"	, "无");
		Riddle riddle551 = new Riddle("	举起碾盘打月亮 	","	 不知天高地厚	", "节气"	, "无");
		Riddle riddle552 = new Riddle("	大年初一生娃娃 	","	 双喜临门	", "节气"	, "无");
		Riddle riddle553 = new Riddle("	初一吃十五的饭 	","	 前吃后空	", "节气"	, "无");
		Riddle riddle554 = new Riddle("	爬高梯摘月亮 	","	 空想	", "节气"	, "无");
		Riddle riddle555 = new Riddle("	月亮里的桂树 	","	 高不可攀	", "节气"	, "无");
		Riddle riddle556 = new Riddle("	三九天吃梅子 	","	 寒酸	", "节气"	, "无");
		Riddle riddle557 = new Riddle("	过年的肥猪 	","	 早晚得杀	", "节气"	, "无");
		Riddle riddle558 = new Riddle("	三十年的旧棉絮 	","	 老套子	", "节气"	, "无");
		Riddle riddle559 = new Riddle("	对着月亮攀谈 	","	 空话连篇	", "节气"	, "无");
		Riddle riddle560 = new Riddle("	茶壶里煮元宵 	","	 满腹心事	", "节气"	, "无");

		dbRManager.insert(riddle1);
		dbRManager.insert(riddle2);
		dbRManager.insert(riddle3);
		dbRManager.insert(riddle4);
		dbRManager.insert(riddle5);
		dbRManager.insert(riddle6);
		dbRManager.insert(riddle7);
		dbRManager.insert(riddle8);
		dbRManager.insert(riddle9);
		dbRManager.insert(riddle10);
		dbRManager.insert(riddle11);
		dbRManager.insert(riddle12);
		dbRManager.insert(riddle13);
		dbRManager.insert(riddle14);
		dbRManager.insert(riddle15);
		dbRManager.insert(riddle16);
		dbRManager.insert(riddle17);
		dbRManager.insert(riddle18);
		dbRManager.insert(riddle19);
		dbRManager.insert(riddle20);
		dbRManager.insert(riddle21);
		dbRManager.insert(riddle22);
		dbRManager.insert(riddle23);
		dbRManager.insert(riddle24);
		dbRManager.insert(riddle25);
		dbRManager.insert(riddle26);
		dbRManager.insert(riddle27);
		dbRManager.insert(riddle28);
		dbRManager.insert(riddle29);
		dbRManager.insert(riddle30);
		dbRManager.insert(riddle31);
		dbRManager.insert(riddle32);
		dbRManager.insert(riddle33);
		dbRManager.insert(riddle34);
		dbRManager.insert(riddle35);
		dbRManager.insert(riddle36);
		dbRManager.insert(riddle37);
		dbRManager.insert(riddle38);
		dbRManager.insert(riddle39);
		dbRManager.insert(riddle40);
		dbRManager.insert(riddle41);
		dbRManager.insert(riddle42);
		dbRManager.insert(riddle43);
		dbRManager.insert(riddle44);
		dbRManager.insert(riddle45);
		dbRManager.insert(riddle46);
		dbRManager.insert(riddle47);
		dbRManager.insert(riddle48);
		dbRManager.insert(riddle49);
		dbRManager.insert(riddle50);
		dbRManager.insert(riddle51);
		dbRManager.insert(riddle52);
		dbRManager.insert(riddle53);
		dbRManager.insert(riddle54);
		dbRManager.insert(riddle55);
		dbRManager.insert(riddle56);
		dbRManager.insert(riddle57);
		dbRManager.insert(riddle58);
		dbRManager.insert(riddle59);
		dbRManager.insert(riddle60);
		dbRManager.insert(riddle61);
		dbRManager.insert(riddle62);
		dbRManager.insert(riddle63);
		dbRManager.insert(riddle64);
		dbRManager.insert(riddle65);
		dbRManager.insert(riddle66);
		dbRManager.insert(riddle67);
		dbRManager.insert(riddle68);
		dbRManager.insert(riddle69);
		dbRManager.insert(riddle70);
		dbRManager.insert(riddle71);
		dbRManager.insert(riddle72);
		dbRManager.insert(riddle73);
		dbRManager.insert(riddle74);
		dbRManager.insert(riddle75);
		dbRManager.insert(riddle76);
		dbRManager.insert(riddle77);
		dbRManager.insert(riddle78);
		dbRManager.insert(riddle79);
		dbRManager.insert(riddle80);
		dbRManager.insert(riddle81);
		dbRManager.insert(riddle82);
		dbRManager.insert(riddle83);
		dbRManager.insert(riddle84);
		dbRManager.insert(riddle85);
		dbRManager.insert(riddle86);
		dbRManager.insert(riddle87);
		dbRManager.insert(riddle88);
		dbRManager.insert(riddle89);
		dbRManager.insert(riddle90);
		dbRManager.insert(riddle91);
		dbRManager.insert(riddle92);
		dbRManager.insert(riddle93);
		dbRManager.insert(riddle94);
		dbRManager.insert(riddle95);
		dbRManager.insert(riddle96);
		dbRManager.insert(riddle97);
		dbRManager.insert(riddle98);
		dbRManager.insert(riddle99);
		dbRManager.insert(riddle100);
		dbRManager.insert(riddle101);
		dbRManager.insert(riddle102);
		dbRManager.insert(riddle103);
		dbRManager.insert(riddle104);
		dbRManager.insert(riddle105);
		dbRManager.insert(riddle106);
		dbRManager.insert(riddle107);
		dbRManager.insert(riddle108);
		dbRManager.insert(riddle109);
		dbRManager.insert(riddle110);
		dbRManager.insert(riddle111);
		dbRManager.insert(riddle112);
		dbRManager.insert(riddle113);
		dbRManager.insert(riddle114);
		dbRManager.insert(riddle115);
		dbRManager.insert(riddle116);
		dbRManager.insert(riddle117);
		dbRManager.insert(riddle118);
		dbRManager.insert(riddle119);
		dbRManager.insert(riddle120);
		dbRManager.insert(riddle121);
		dbRManager.insert(riddle122);
		dbRManager.insert(riddle123);
		dbRManager.insert(riddle124);
		dbRManager.insert(riddle125);
		dbRManager.insert(riddle126);
		dbRManager.insert(riddle127);
		dbRManager.insert(riddle128);
		dbRManager.insert(riddle129);
		dbRManager.insert(riddle130);
		dbRManager.insert(riddle131);
		dbRManager.insert(riddle132);
		dbRManager.insert(riddle133);
		dbRManager.insert(riddle134);
		dbRManager.insert(riddle135);
		dbRManager.insert(riddle136);
		dbRManager.insert(riddle137);
		dbRManager.insert(riddle138);
		dbRManager.insert(riddle139);
		dbRManager.insert(riddle140);
		dbRManager.insert(riddle141);
		dbRManager.insert(riddle142);
		dbRManager.insert(riddle143);
		dbRManager.insert(riddle144);
		dbRManager.insert(riddle145);
		dbRManager.insert(riddle146);
		dbRManager.insert(riddle147);
		dbRManager.insert(riddle148);
		dbRManager.insert(riddle149);
		dbRManager.insert(riddle150);
		dbRManager.insert(riddle151);
		dbRManager.insert(riddle152);
		dbRManager.insert(riddle153);
		dbRManager.insert(riddle154);
		dbRManager.insert(riddle155);
		dbRManager.insert(riddle156);
		dbRManager.insert(riddle157);
		dbRManager.insert(riddle158);
		dbRManager.insert(riddle159);
		dbRManager.insert(riddle160);
		dbRManager.insert(riddle161);
		dbRManager.insert(riddle162);
		dbRManager.insert(riddle163);
		dbRManager.insert(riddle164);
		dbRManager.insert(riddle165);
		dbRManager.insert(riddle166);
		dbRManager.insert(riddle167);
		dbRManager.insert(riddle168);
		dbRManager.insert(riddle169);
		dbRManager.insert(riddle170);
		dbRManager.insert(riddle171);
		dbRManager.insert(riddle172);
		dbRManager.insert(riddle173);
		dbRManager.insert(riddle174);
		dbRManager.insert(riddle175);
		dbRManager.insert(riddle176);
		dbRManager.insert(riddle177);
		dbRManager.insert(riddle178);
		dbRManager.insert(riddle179);
		dbRManager.insert(riddle180);
		dbRManager.insert(riddle181);
		dbRManager.insert(riddle182);
		dbRManager.insert(riddle183);
		dbRManager.insert(riddle184);
		dbRManager.insert(riddle185);
		dbRManager.insert(riddle186);
		dbRManager.insert(riddle187);
		dbRManager.insert(riddle188);
		dbRManager.insert(riddle189);
		dbRManager.insert(riddle190);
		dbRManager.insert(riddle191);
		dbRManager.insert(riddle192);
		dbRManager.insert(riddle193);
		dbRManager.insert(riddle194);
		dbRManager.insert(riddle195);
		dbRManager.insert(riddle196);
		dbRManager.insert(riddle197);
		dbRManager.insert(riddle198);
		dbRManager.insert(riddle199);
		dbRManager.insert(riddle200);
		dbRManager.insert(riddle201);
		dbRManager.insert(riddle202);
		dbRManager.insert(riddle203);
		dbRManager.insert(riddle204);
		dbRManager.insert(riddle205);
		dbRManager.insert(riddle206);
		dbRManager.insert(riddle207);
		dbRManager.insert(riddle208);
		dbRManager.insert(riddle209);
		dbRManager.insert(riddle210);
		dbRManager.insert(riddle211);
		dbRManager.insert(riddle212);
		dbRManager.insert(riddle213);
		dbRManager.insert(riddle214);
		dbRManager.insert(riddle215);
		dbRManager.insert(riddle216);
		dbRManager.insert(riddle217);
		dbRManager.insert(riddle218);
		dbRManager.insert(riddle219);
		dbRManager.insert(riddle220);
		dbRManager.insert(riddle221);
		dbRManager.insert(riddle222);
		dbRManager.insert(riddle223);
		dbRManager.insert(riddle224);
		dbRManager.insert(riddle225);
		dbRManager.insert(riddle226);
		dbRManager.insert(riddle227);
		dbRManager.insert(riddle228);
		dbRManager.insert(riddle229);
		dbRManager.insert(riddle230);
		dbRManager.insert(riddle231);
		dbRManager.insert(riddle232);
		dbRManager.insert(riddle233);
		dbRManager.insert(riddle234);
		dbRManager.insert(riddle235);
		dbRManager.insert(riddle236);
		dbRManager.insert(riddle237);
		dbRManager.insert(riddle238);
		dbRManager.insert(riddle239);
		dbRManager.insert(riddle240);
		dbRManager.insert(riddle241);
		dbRManager.insert(riddle242);
		dbRManager.insert(riddle243);
		dbRManager.insert(riddle244);
		dbRManager.insert(riddle245);
		dbRManager.insert(riddle246);
		dbRManager.insert(riddle247);
		dbRManager.insert(riddle248);
		dbRManager.insert(riddle249);
		dbRManager.insert(riddle250);
		dbRManager.insert(riddle251);
		dbRManager.insert(riddle252);
		dbRManager.insert(riddle253);
		dbRManager.insert(riddle254);
		dbRManager.insert(riddle255);
		dbRManager.insert(riddle256);
		dbRManager.insert(riddle257);
		dbRManager.insert(riddle258);
		dbRManager.insert(riddle259);
		dbRManager.insert(riddle260);
		dbRManager.insert(riddle261);
		dbRManager.insert(riddle262);
		dbRManager.insert(riddle263);
		dbRManager.insert(riddle264);
		dbRManager.insert(riddle265);
		dbRManager.insert(riddle266);
		dbRManager.insert(riddle267);
		dbRManager.insert(riddle268);
		dbRManager.insert(riddle269);
		dbRManager.insert(riddle270);
		dbRManager.insert(riddle271);
		dbRManager.insert(riddle272);
		dbRManager.insert(riddle273);
		dbRManager.insert(riddle274);
		dbRManager.insert(riddle275);
		dbRManager.insert(riddle276);
		dbRManager.insert(riddle277);
		dbRManager.insert(riddle278);
		dbRManager.insert(riddle279);
		dbRManager.insert(riddle280);
		dbRManager.insert(riddle281);
		dbRManager.insert(riddle282);
		dbRManager.insert(riddle283);
		dbRManager.insert(riddle284);
		dbRManager.insert(riddle285);
		dbRManager.insert(riddle286);
		dbRManager.insert(riddle287);
		dbRManager.insert(riddle288);
		dbRManager.insert(riddle289);
		dbRManager.insert(riddle290);
		dbRManager.insert(riddle291);
		dbRManager.insert(riddle292);
		dbRManager.insert(riddle293);
		dbRManager.insert(riddle294);
		dbRManager.insert(riddle295);
		dbRManager.insert(riddle296);
		dbRManager.insert(riddle297);
		dbRManager.insert(riddle298);
		dbRManager.insert(riddle299);
		dbRManager.insert(riddle300);
		dbRManager.insert(riddle301);
		dbRManager.insert(riddle302);
		dbRManager.insert(riddle303);
		dbRManager.insert(riddle304);
		dbRManager.insert(riddle305);
		dbRManager.insert(riddle306);
		dbRManager.insert(riddle307);
		dbRManager.insert(riddle308);
		dbRManager.insert(riddle309);
		dbRManager.insert(riddle310);
		dbRManager.insert(riddle311);
		dbRManager.insert(riddle312);
		dbRManager.insert(riddle313);
		dbRManager.insert(riddle314);
		dbRManager.insert(riddle315);
		dbRManager.insert(riddle316);
		dbRManager.insert(riddle317);
		dbRManager.insert(riddle318);
		dbRManager.insert(riddle319);
		dbRManager.insert(riddle320);
		dbRManager.insert(riddle321);
		dbRManager.insert(riddle322);
		dbRManager.insert(riddle323);
		dbRManager.insert(riddle324);
		dbRManager.insert(riddle325);
		dbRManager.insert(riddle326);
		dbRManager.insert(riddle327);
		dbRManager.insert(riddle328);
		dbRManager.insert(riddle329);
		dbRManager.insert(riddle330);
		dbRManager.insert(riddle331);
		dbRManager.insert(riddle332);
		dbRManager.insert(riddle333);
		dbRManager.insert(riddle334);
		dbRManager.insert(riddle335);
		dbRManager.insert(riddle336);
		dbRManager.insert(riddle337);
		dbRManager.insert(riddle338);
		dbRManager.insert(riddle339);
		dbRManager.insert(riddle340);
		dbRManager.insert(riddle341);
		dbRManager.insert(riddle342);
		dbRManager.insert(riddle343);
		dbRManager.insert(riddle344);
		dbRManager.insert(riddle345);
		dbRManager.insert(riddle346);
		dbRManager.insert(riddle347);
		dbRManager.insert(riddle348);
		dbRManager.insert(riddle349);
		dbRManager.insert(riddle350);
		dbRManager.insert(riddle351);
		dbRManager.insert(riddle352);
		dbRManager.insert(riddle353);
		dbRManager.insert(riddle354);
		dbRManager.insert(riddle355);
		dbRManager.insert(riddle356);
		dbRManager.insert(riddle357);
		dbRManager.insert(riddle358);
		dbRManager.insert(riddle359);
		dbRManager.insert(riddle360);
		dbRManager.insert(riddle361);
		dbRManager.insert(riddle362);
		dbRManager.insert(riddle363);
		dbRManager.insert(riddle364);
		dbRManager.insert(riddle365);
		dbRManager.insert(riddle366);
		dbRManager.insert(riddle367);
		dbRManager.insert(riddle368);
		dbRManager.insert(riddle369);
		dbRManager.insert(riddle370);
		dbRManager.insert(riddle371);
		dbRManager.insert(riddle372);
		dbRManager.insert(riddle373);
		dbRManager.insert(riddle374);
		dbRManager.insert(riddle375);
		dbRManager.insert(riddle376);
		dbRManager.insert(riddle377);
		dbRManager.insert(riddle378);
		dbRManager.insert(riddle379);
		dbRManager.insert(riddle380);
		dbRManager.insert(riddle381);
		dbRManager.insert(riddle382);
		dbRManager.insert(riddle383);
		dbRManager.insert(riddle384);
		dbRManager.insert(riddle385);
		dbRManager.insert(riddle386);
		dbRManager.insert(riddle387);
		dbRManager.insert(riddle388);
		dbRManager.insert(riddle389);
		dbRManager.insert(riddle390);
		dbRManager.insert(riddle391);
		dbRManager.insert(riddle392);
		dbRManager.insert(riddle393);
		dbRManager.insert(riddle394);
		dbRManager.insert(riddle395);
		dbRManager.insert(riddle396);
		dbRManager.insert(riddle397);
		dbRManager.insert(riddle398);
		dbRManager.insert(riddle399);
		dbRManager.insert(riddle400);
		dbRManager.insert(riddle401);
		dbRManager.insert(riddle402);
		dbRManager.insert(riddle403);
		dbRManager.insert(riddle404);
		dbRManager.insert(riddle405);
		dbRManager.insert(riddle406);
		dbRManager.insert(riddle407);
		dbRManager.insert(riddle408);
		dbRManager.insert(riddle409);
		dbRManager.insert(riddle410);
		dbRManager.insert(riddle411);
		dbRManager.insert(riddle412);
		dbRManager.insert(riddle413);
		dbRManager.insert(riddle414);
		dbRManager.insert(riddle415);
		dbRManager.insert(riddle416);
		dbRManager.insert(riddle417);
		dbRManager.insert(riddle418);
		dbRManager.insert(riddle419);
		dbRManager.insert(riddle420);
		dbRManager.insert(riddle421);
		dbRManager.insert(riddle422);
		dbRManager.insert(riddle423);
		dbRManager.insert(riddle424);
		dbRManager.insert(riddle425);
		dbRManager.insert(riddle426);
		dbRManager.insert(riddle427);
		dbRManager.insert(riddle428);
		dbRManager.insert(riddle429);
		dbRManager.insert(riddle430);
		dbRManager.insert(riddle431);
		dbRManager.insert(riddle432);
		dbRManager.insert(riddle433);
		dbRManager.insert(riddle434);
		dbRManager.insert(riddle435);
		dbRManager.insert(riddle436);
		dbRManager.insert(riddle437);
		dbRManager.insert(riddle438);
		dbRManager.insert(riddle439);
		dbRManager.insert(riddle440);
		dbRManager.insert(riddle441);
		dbRManager.insert(riddle442);
		dbRManager.insert(riddle443);
		dbRManager.insert(riddle444);
		dbRManager.insert(riddle445);
		dbRManager.insert(riddle446);
		dbRManager.insert(riddle447);
		dbRManager.insert(riddle448);
		dbRManager.insert(riddle449);
		dbRManager.insert(riddle450);
		dbRManager.insert(riddle451);
		dbRManager.insert(riddle452);
		dbRManager.insert(riddle453);
		dbRManager.insert(riddle454);
		dbRManager.insert(riddle455);
		dbRManager.insert(riddle456);
		dbRManager.insert(riddle457);
		dbRManager.insert(riddle458);
		dbRManager.insert(riddle459);
		dbRManager.insert(riddle460);
		dbRManager.insert(riddle461);
		dbRManager.insert(riddle462);
		dbRManager.insert(riddle463);
		dbRManager.insert(riddle464);
		dbRManager.insert(riddle465);
		dbRManager.insert(riddle466);
		dbRManager.insert(riddle467);
		dbRManager.insert(riddle468);
		dbRManager.insert(riddle469);
		dbRManager.insert(riddle470);
		dbRManager.insert(riddle471);
		dbRManager.insert(riddle472);
		dbRManager.insert(riddle473);
		dbRManager.insert(riddle474);
		dbRManager.insert(riddle475);
		dbRManager.insert(riddle476);
		dbRManager.insert(riddle477);
		dbRManager.insert(riddle478);
		dbRManager.insert(riddle479);
		dbRManager.insert(riddle480);
		dbRManager.insert(riddle481);
		dbRManager.insert(riddle482);
		dbRManager.insert(riddle483);
		dbRManager.insert(riddle484);
		dbRManager.insert(riddle485);
		dbRManager.insert(riddle486);
		dbRManager.insert(riddle487);
		dbRManager.insert(riddle488);
		dbRManager.insert(riddle489);
		dbRManager.insert(riddle490);
		dbRManager.insert(riddle491);
		dbRManager.insert(riddle492);
		dbRManager.insert(riddle493);
		dbRManager.insert(riddle494);
		dbRManager.insert(riddle495);
		dbRManager.insert(riddle496);
		dbRManager.insert(riddle497);
		dbRManager.insert(riddle498);
		dbRManager.insert(riddle499);
		dbRManager.insert(riddle500);
		dbRManager.insert(riddle501);
		dbRManager.insert(riddle502);
		dbRManager.insert(riddle503);
		dbRManager.insert(riddle504);
		dbRManager.insert(riddle505);
		dbRManager.insert(riddle506);
		dbRManager.insert(riddle507);
		dbRManager.insert(riddle508);
		dbRManager.insert(riddle509);
		dbRManager.insert(riddle510);
		dbRManager.insert(riddle511);
		dbRManager.insert(riddle512);
		dbRManager.insert(riddle513);
		dbRManager.insert(riddle514);
		dbRManager.insert(riddle515);
		dbRManager.insert(riddle516);
		dbRManager.insert(riddle517);
		dbRManager.insert(riddle518);
		dbRManager.insert(riddle519);
		dbRManager.insert(riddle520);
		dbRManager.insert(riddle521);
		dbRManager.insert(riddle522);
		dbRManager.insert(riddle523);
		dbRManager.insert(riddle524);
		dbRManager.insert(riddle525);
		dbRManager.insert(riddle526);
		dbRManager.insert(riddle527);
		dbRManager.insert(riddle528);
		dbRManager.insert(riddle529);
		dbRManager.insert(riddle530);
		dbRManager.insert(riddle531);
		dbRManager.insert(riddle532);
		dbRManager.insert(riddle533);
		dbRManager.insert(riddle534);
		dbRManager.insert(riddle535);
		dbRManager.insert(riddle536);
		dbRManager.insert(riddle537);
		dbRManager.insert(riddle538);
		dbRManager.insert(riddle539);
		dbRManager.insert(riddle540);
		dbRManager.insert(riddle541);
		dbRManager.insert(riddle542);
		dbRManager.insert(riddle543);
		dbRManager.insert(riddle544);
		dbRManager.insert(riddle545);
		dbRManager.insert(riddle546);
		dbRManager.insert(riddle547);
		dbRManager.insert(riddle548);
		dbRManager.insert(riddle549);
		dbRManager.insert(riddle550);
		dbRManager.insert(riddle551);
		dbRManager.insert(riddle552);
		dbRManager.insert(riddle553);
		dbRManager.insert(riddle554);
		dbRManager.insert(riddle555);
		dbRManager.insert(riddle556);
		dbRManager.insert(riddle557);
		dbRManager.insert(riddle558);
		dbRManager.insert(riddle559);
		dbRManager.insert(riddle560);

	}

	@Override
	public boolean onKeyDown(int keyCode, KeyEvent event) {
		if (keyCode == KeyEvent.KEYCODE_BACK
				|| keyCode == KeyEvent.KEYCODE_HOME) {
			return true;
		}
		return super.onKeyDown(keyCode, event);
	}
}
